project_id = "ohkswkuenwbntukkmxso"

[functions.admin-bootstrap]
verify_jwt = true

[functions.issue-member-login]
verify_jwt = true

[functions.merge-family]
verify_jwt = true

[functions.reset-member-password]
verify_jwt = true

[functions.delete-member]
verify_jwt = true

[functions.manage-role]
verify_jwt = true
